"""
Beancount journal entry generator.
Converts classified Transaction domain objects to Beancount format text.
Does NOT depend on the beancount library — generates correct format directly.
"""
from dataclasses import dataclass
from decimal import Decimal

from app.domain.beancount.account_resolver import (
    INCOME_ACCOUNT,
    TRANSFER_ACCOUNT,
    resolve_asset_account,
    resolve_expense_account,
)
from app.domain.transaction.models import Transaction, TransactionDirection


@dataclass
class BeancountPosting:
    account: str
    amount: Decimal
    currency: str

    def render(self) -> str:
        sign = "" if self.amount >= 0 else ""
        return f"  {self.account:<40}  {self.amount:>10.2f} {self.currency}"


@dataclass
class BeancountEntry:
    transaction_id: str
    date: str          # YYYY-MM-DD
    flag: str          # '*' completed, '!' pending
    payee: str
    narration: str
    postings: list[BeancountPosting]
    tags: list[str]

    def render(self) -> str:
        payee_part = f'"{self.payee}" ' if self.payee else ""
        tag_part = " ".join(f"#{t}" for t in self.tags) + " " if self.tags else ""
        header = f'{self.date} {self.flag} {tag_part}{payee_part}"{self.narration}"'
        lines = [header]
        for posting in self.postings:
            lines.append(posting.render())
        return "\n".join(lines)


class BeancountEngine:
    def generate_entry(self, tx: Transaction) -> BeancountEntry:
        amount = Decimal(str(tx.amount))
        asset_account = resolve_asset_account(tx.source)

        if tx.direction == TransactionDirection.EXPENSE:
            expense_account = resolve_expense_account(tx.category_l1, tx.category_l2)
            postings = [
                BeancountPosting(expense_account, amount, tx.currency),
                BeancountPosting(asset_account, -amount, tx.currency),
            ]
        elif tx.direction == TransactionDirection.INCOME:
            postings = [
                BeancountPosting(asset_account, amount, tx.currency),
                BeancountPosting(INCOME_ACCOUNT, -amount, tx.currency),
            ]
        else:  # TRANSFER
            postings = [
                BeancountPosting(TRANSFER_ACCOUNT, amount, tx.currency),
                BeancountPosting(asset_account, -amount, tx.currency),
            ]

        return BeancountEntry(
            transaction_id=tx.id,
            date=tx.transaction_at.strftime("%Y-%m-%d"),
            flag="*",
            payee=tx.merchant or "",
            narration=tx.description or "",
            postings=postings,
            tags=[tx.source.value],
        )

    def generate_entries(self, transactions: list[Transaction]) -> list[BeancountEntry]:
        entries = []
        for tx in transactions:
            try:
                entries.append(self.generate_entry(tx))
            except Exception:
                pass  # Skip malformed transactions
        return entries

    def render_ledger(self, transactions: list[Transaction], include_header: bool = True) -> str:
        entries = self.generate_entries(transactions)
        # Sort by date
        entries.sort(key=lambda e: e.date)

        parts: list[str] = []
        if include_header:
            parts.append('; Generated by Beancount Bot')
            parts.append('option "operating_currency" "CNY"')
            parts.append('')
            # Account open directives
            all_accounts: set[str] = set()
            for entry in entries:
                for p in entry.postings:
                    all_accounts.add(p.account)
            min_date = entries[0].date if entries else "2020-01-01"
            for acc in sorted(all_accounts):
                parts.append(f'{min_date} open {acc} CNY')
            parts.append('')

        for entry in entries:
            parts.append(entry.render())
            parts.append('')

        return "\n".join(parts)
